# # business_definition_loader.py

# class BusinessDefinitionLoader:

#     @staticmethod
#     def get_definitions():

#         return """
# Revenue =
# SUM(orderdetails.quantityOrdered * orderdetails.priceEach)

# Customer Payments =
# SUM(payments.amount)

# Order Count =
# COUNT(orders.orderNumber)

# Average Order Value =
# Revenue / Order Count

# Top Customers =
# Customers ranked by Customer Payments

# Top Product Lines =
# Product lines ranked by Revenue

# Top Sales Representatives =
# Employees ranked by Revenue

# Customer Revenue =
# Revenue generated by all orders placed by a customer

# Office Revenue =
# Revenue generated by customers assigned to employees in an office
# """








# business_definition_loader.py

# class BusinessDefinitionLoader:

#     @staticmethod
#     def get_definitions():

#         return """
# Revenue =
# SUM(payment.amount)

# Customer Count =
# COUNT(DISTINCT customer.customer_id)

# Rental Count =
# COUNT(DISTINCT rental.rental_id)

# Film Count =
# COUNT(DISTINCT film.film_id)

# Store Count =
# COUNT(DISTINCT store.store_id)

# Average Payment =
# AVG(payment.amount)

# Top Customers =
# Customers ranked by total payment amount

# Revenue By Category =
# Total payment amount grouped by film category

# Top Rented Films =
# Films ranked by rental count

# Customer Lifetime Value =
# Total payment amount generated by a customer

# Store Revenue =
# Total payment amount generated by rentals processed by a store

# Active Customers =
# Customers who have rented at least one film

# Rental Revenue =
# Revenue generated from film rentals
# """


# class BusinessDefinitionLoader:

#     @staticmethod
#     def get_definitions():

#         return """
# Revenue =
# SUM(FactInternetSales.SalesAmount)

# Customer Count =
# COUNT(DISTINCT DimCustomer.CustomerKey)

# Product Count =
# COUNT(DISTINCT DimProduct.ProductKey)

# Order Count =
# COUNT(DISTINCT FactInternetSales.SalesOrderNumber)

# Top Customers =
# Customers ranked by total SalesAmount

# Revenue By Territory =
# SUM(FactInternetSales.SalesAmount)
# grouped by DimSalesTerritory

# Revenue By Product Category =
# SUM(FactInternetSales.SalesAmount)
# grouped by DimProductCategory

# Top Selling Products =
# Products ranked by total OrderQuantity

# Customer Lifetime Value =
# Total SalesAmount per customer

# Calendar Year =
# DimDate.CalendarYear

# Fiscal Year =
# DimDate.FiscalYear

# Quantity Sold =
# SUM(FactInternetSales.OrderQuantity)

# Sales Territory =
# DimSalesTerritory

# Product Category =
# DimProductCategory

# Product Subcategory =
# DimProductSubcategory

# Customer Geography =
# DimGeography

# Average Sales Amount =
# AVG(FactInternetSales.SalesAmount)
# """






class BusinessDefinitionLoader:

    @staticmethod
    def get_definitions():

        return """
Revenue =
SUM(FactInternetSales.SalesAmount)

Customer Count =
COUNT(DISTINCT DimCustomer.CustomerKey)

Product Count =
COUNT(DISTINCT DimProduct.ProductKey)

Order Count =
COUNT(DISTINCT FactInternetSales.SalesOrderNumber)

Quantity Sold =
SUM(FactInternetSales.OrderQuantity)

Average Sales Amount =
AVG(FactInternetSales.SalesAmount)

Customer Lifetime Value =
Total SalesAmount generated by a customer

Top Customers =
Customers ranked by total SalesAmount

Top Selling Products =
Products ranked by total OrderQuantity

Sales Territory =
DimSalesTerritory

Customer Geography =
DimGeography

Calendar Year =
DimDate.CalendarYear

Fiscal Year =
DimDate.FiscalYear

Product Category =
DimProductCategory

Product Subcategory =
DimProductSubcategory

Revenue By Territory =
SUM(FactInternetSales.SalesAmount)
grouped by DimSalesTerritory

Revenue By Product Category =
SUM(FactInternetSales.SalesAmount)
grouped by DimProductCategory

Revenue By Year =
SUM(FactInternetSales.SalesAmount)
grouped by DimDate.CalendarYear

Revenue By Product =
SUM(FactInternetSales.SalesAmount)
grouped by DimProduct

Customer Sales =
SUM(FactInternetSales.SalesAmount)
grouped by DimCustomer

--------------------------------------------------
ADVENTUREWORKS JOIN RULES
--------------------------------------------------

FactInternetSales joins DimCustomer using:

FactInternetSales.CustomerKey
=
DimCustomer.CustomerKey

FactInternetSales joins DimDate using:

FactInternetSales.OrderDateKey
=
DimDate.DateKey

FactInternetSales joins DimProduct using:

FactInternetSales.ProductKey
=
DimProduct.ProductKey

FactInternetSales joins DimSalesTerritory using:

FactInternetSales.SalesTerritoryKey
=
DimSalesTerritory.SalesTerritoryKey

--------------------------------------------------
PRODUCT CATEGORY JOIN PATH
--------------------------------------------------

To access Product Categories use:

FactInternetSales
-> DimProduct
using ProductKey

DimProduct
-> DimProductSubcategory
using ProductSubcategoryKey

DimProductSubcategory
-> DimProductCategory
using ProductCategoryKey

DO NOT JOIN:

DimProduct
directly to
DimProductCategory

This relationship does not exist.

--------------------------------------------------
CATEGORY ANALYTICS
--------------------------------------------------

Revenue By Category

FactInternetSales
-> DimProduct
-> DimProductSubcategory
-> DimProductCategory

Category Revenue

SUM(FactInternetSales.SalesAmount)
grouped by
DimProductCategory.EnglishProductCategoryName

Top Categories

Rank categories by
SUM(FactInternetSales.SalesAmount)

Category Trend Analysis

FactInternetSales
-> DimDate
-> CalendarYear

FactInternetSales
-> DimProduct
-> DimProductSubcategory
-> DimProductCategory

--------------------------------------------------
TIME ANALYTICS
--------------------------------------------------

Year =
DimDate.CalendarYear

Month =
DimDate.EnglishMonthName

Quarter =
DimDate.CalendarQuarter

Fiscal Year =
DimDate.FiscalYear

Year Over Year Growth =
Compare revenue grouped by CalendarYear

Monthly Revenue =
SUM(FactInternetSales.SalesAmount)
grouped by month

--------------------------------------------------
IMPORTANT
--------------------------------------------------

Never invent columns.

Never invent relationships.

Always follow the foreign key paths provided in
the schema relationships section.

If multiple join paths are possible,
prefer the path defined above.
"""