# # business_definition_loader.py

# class BusinessDefinitionLoader:

#     @staticmethod
#     def get_definitions():

#         return """
# Revenue =
# SUM(orderdetails.quantityOrdered * orderdetails.priceEach)

# Customer Payments =
# SUM(payments.amount)

# Order Count =
# COUNT(orders.orderNumber)

# Average Order Value =
# Revenue / Order Count

# Top Customers =
# Customers ranked by Customer Payments

# Top Product Lines =
# Product lines ranked by Revenue

# Top Sales Representatives =
# Employees ranked by Revenue

# Customer Revenue =
# Revenue generated by all orders placed by a customer

# Office Revenue =
# Revenue generated by customers assigned to employees in an office
# """



# business_definition_loader.py

class BusinessDefinitionLoader:

    @staticmethod
    def get_definitions():

        return """
Revenue =
SUM(payment.amount)

Customer Count =
COUNT(DISTINCT customer.customer_id)

Rental Count =
COUNT(DISTINCT rental.rental_id)

Film Count =
COUNT(DISTINCT film.film_id)

Store Count =
COUNT(DISTINCT store.store_id)

Average Payment =
AVG(payment.amount)

Top Customers =
Customers ranked by total payment amount

Revenue By Category =
Total payment amount grouped by film category

Top Rented Films =
Films ranked by rental count

Customer Lifetime Value =
Total payment amount generated by a customer

Store Revenue =
Total payment amount generated by rentals processed by a store

Active Customers =
Customers who have rented at least one film

Rental Revenue =
Revenue generated from film rentals
"""